my_first_project/basic_app/urls.py
from django.conf.urls import url
from basic_app import views
from django.urls import path

#template_tagging
app_name = "basic_app"

urlpatterns = [
url(r'^$',views.myfunc,name='myfunc'),
url(r'^data_record',views.MTV,name='MTV'),
url(r'^formpage',views.form_name_view,name='form_name'),
url(r'^template_tagging',views.template_tagging,name='template_tagging'),
url(r'^register',views.register,name='register'),
url(r'^user_login/$',views.user_login,name='user_login')
]

my_first_project/my_first_project/urls.py
from django.contrib import admin
from django.urls import path


from django.conf.urls import url
from django.conf.urls import include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^more/',include('basic_app.urls')),
    url(r'^logout/$',views.user_logout,name = 'logout'),
    url(r'^special/',views.special,name='special')
]

my_first_project/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User #this is for last class

class Topic(models.Model):
    Top_name = models.CharField(max_length=264,unique=True)

    def __str__(self):
        return self.Top_name

class WebPage(models.Model):
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    name = models.CharField(max_length=264,unique=True)
    url =  models.URLField(unique = True)

    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    name = models.ForeignKey(WebPage,on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)


# the code below if from fifth lecture of Django
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    # with the above line, the "user" has an one to one mapping wth the django in-built "User" module
    #i.e. Username, Email, Password, First Name, Last NAME
    # Directly inheriting from "User" class in UserProfileInfo is not good practice
    # that is why we have done onetoone mapping. Now we will add some more columns of our wish to the "User" class

    portfolio = models.URLField (blank = True)
    profile_pic = models.ImageField(upload_to = 'profile_pics',blank=True)

    def __str__(self):
        return self.user.username
        # where username is coming from the default username column of Django User class

my_first_project/basic_app/forms.py
from django import forms

from django.core import validators

from basic_app.models import UserProfileInfo

from django.contrib.auth.models import User


def check_for_z(inp_value):
    if inp_value[0].lower() !='z':
        raise forms.ValidationError("Name NEEDS TO START WITH Z")

class FormName(forms.Form):
    name = forms.CharField(validators=[check_for_z])
    email = forms.EmailField(label='Enter your email here')
    ver_email = forms.EmailField(label='Enter your Email one more time')
    text =  forms.CharField(widget=forms.Textarea)

    BotCatcher = forms.CharField(required=False,
                                widget=forms.HiddenInput,
                                validators=[validators.MaxLengthValidator(0)])
    # BotCatcher is a hidden tag which is to catch a Bot which is tryring to jam your browser
    # by putting in false data.
    # this field will not be visble to normal user hence MaxLengthValidator will be 0
    # but Bot operated not with html page, but the inspect mode and set a "value" tag there
    #here, it will be trapped since the length value shall be 0 but bot is assigning this value something and hence it will be trapped

    def clean(self):
        all_data_in_clean = super().clean()
        Email = all_data_in_clean['email']
        VEmail = all_data_in_clean['ver_email']

        if Email !=VEmail:
            raise forms.ValidationError('Make sure your emails match')
        else:
            print(Email)
            print(VEmail)


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio','profile_pic')

my_first_project/basic_app/views.py
from django.shortcuts import render

#######################from Nikhil ########################3

from basic_app.models import Topic,WebPage,AccessRecord
from . import forms
from basic_app.forms import UserForm,UserProfileInfoForm
# Create your views here.

###################imports for login / logout of users #########################
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
################################################################################

def index(nikhil):
    """
    This function is for the practice of html tagging
    """
    my_dict = {'insert_me':"Hello, I am due to HTML Tagging",'number_entry':30}

    return render(nikhil,"basic_app/index.html",context=my_dict)


def myfunc(nikhil):
    #return HttpResponse("<em>Yo Yo, you need to give something meaningfull, after  / </em>") # each views.py file should return an HttpResponse object
    return render(nikhil,"basic_app/landing_page.html")

def MTV(mohini):
    webpg_list = AccessRecord.objects.order_by('date')
    new_dict = {'Date_List':webpg_list}
    return render(mohini,"basic_app/MTV_practice.html",context=new_dict)

def form_name_view(request):
    form = forms.FormName()
    if request.method == 'POST':
        form = forms.FormName(request.POST)

        if form.is_valid():
            print(form.cleaned_data['name'])

    return render(request,'basic_app/form_page.html',{'form':form})

#################### This code is for template tagging. Django level 4 #########

def template_tagging(request):
    return render(request, 'basic_app/relative.html')

################################################################################

#################### Django level 5 ###########################################

def register(request):
    registered=False

    if request.method=='POST':
        user_form = UserForm(data = request.POST)
        portfolio_form = UserProfileInfoForm(data = request.POST)

        if user_form.is_valid() and portfolio_form.is_valid():
            user = user_form.save() # Here, we write data to .db file
            user.set_password(user.password)
            user.save()

            profile = portfolio_form.save(commit = False) # Here we do not write data to database
            profile.user = user
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()

            registered = True
        else:
            print(user_form.errors,portfolio_form.errors)
    else:
        user_form = UserForm()
        portfolio_form = UserProfileInfoForm()

    return render(request,'basic_app/registration.html',{'registered':registered,'user_form':user_form,'profile_form':portfolio_form})



################################################################################
def user_login(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
                if user.is_active:
                    login(request,user)
                    return HttpResponseRedirect(reverse("index"))
                else:
                    return HttpResponse("ACCOUNT NOT ACTIVE")

        else:
            print("Someone tried to login but failed")
            print('Username : {} and Password : {}'.format(username,password) )
            return HttpResponse("Invalid Login Details")
    else:
         return render(request,'basic_app/login.html',{})

@login_required
def user_logout(request):
    """
    logically, the user shall logout only when he/she is logged in
    If we see the code in as stand-alone, we find, there is nothing like a IF loop saying that execute this function only when user is logged in
    These all complex stuff is taken cared by just one decorator written above the def
    """
    logout(request)
    return HttpResponseRedirect(reverse("index"))

@login_required
def special(request):
    """
    similar as above, this func will require the user logged in to work. This is due to the decorator
    """
    return HttpResponse("Your are logged in")

my_first_project/templates/basic_app/BASE_html.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Welcome</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <body>
  </head>
  <body>

    <nav class='navbar navbar-inverse'>
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Welcome</a>

      </div>
      <ul class="nav navbar-nav">
        <li><a href="{% url 'basic_app:myfunc' %}">Landing Page</a></li>
        <li><a href="{% url 'basic_app:MTV' %}">Data Record</a></li>
        <li><a href="{% url 'basic_app:form_name' %}">Form</a></li>
        <li><a href="{% url 'basic_app:register'  %}">Register</a></li>
        <li><a href="{% url 'admin:index'  %}">Admin Page</a></li>

        {% if user.is_authenticated %}
          <li><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}
            <li><a href="{% url 'basic_app:user_login' %}">Login</a></li>
        {% endif %}

      </ul>

    </nav>

    <!-- the above syntax is template tagging. Here important is the Global Variable defined in urls.py in App folder -->
    <!-- In "basic_app:MTV"   The "basic_app" is the string assignment of Global Variable. Matching of this name is compulsory -->
    <!-- and "MTV" is the 'Name' attribute of 'url' in 'urlpatterns' list  -->
    <div class="container">
      {% block my_block %}

      <!-- So, the rest of stuff in this html will we constant for other htmls. The stuff inside this block will be from other html. -->
      <!-- Tis place is kind of blocker space for the data from other HTML -->

      {% endblock %}

    </div>

  </body>
</html>

my_first_project/templates/basic_app/MTV_practice.html
<!DOCTYPE html>
{% extends "basic_app/BASE_html.html" %}
{% load static %}

{% block my_block %}

<h1>Hello, this is data representation page</h1>
<h2>This html file reads the data from .db file and displays here.</h2>
<h2>This html file has used FOR loop and IF loop...That is Interesting</h2>
<p></p>
<p></p>

<div class="djangotwo">
  <!-- This is called template tagging. This particular line checks if we have the key "Date_List" in views.py. If yes, then go in loop -->
  {% if Date_List %}
    <table>
      <thead>
        <th>Site Name</th>
        <th>date Accessed</th>
      </thead>

      {% for DATA in Date_List %}
        <tr>
          <td>{{ DATA.name }}</td>
          <td>{{ DATA.date }}</td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
      <p>NO ACCESS RECORD FOUND</p>
  {% endif %}

</div>

{% endblock %}

my_first_project/templates/basic_app/form_page.html
<!DOCTYPE html>
{% extends "basic_app/BASE_html.html" %}


{% block my_block %}
<div class="container">
  <form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" name="btn btn-primary" value="SubmiT">

  </form>
</div>

{% endblock %}

my_first_project/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/BASE_html.html" %}
{% load static %}
{% load my_file %}

{% block my_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Hello, this is index.html</h1>
    <img src="{% static "images/django.png" %}" alt="Uh oh!! No Image found">

    <h3>{{ insert_me|my_filter }}</h3>
    <!-- above, customized_filter which is defined in templatetags folder -->
    <h3>{{ number_entry|add:"10" }}</h3>
    <!-- above, add is default Templateflter of python -->

    <p></p>
    <p></p>
    <h3>/more for further options</h3>
  </div>
</div>
{% endblock %}

my_first_project/templates/basic_app/index_1.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>First App</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static "css/mystyle_1.css" %}"/>
  </head>
  <body>
    <div class="container">
      <div class="jumbotron">

        <h1>Hello, this is index.html</h1>
        <img src="{% static "images/django.png" %}" alt="Uh oh!! No Image found">

        {{ insert_me }}
        <p></p>
        <p></p>
        <h3>/more for further options</h3>



      </div>

    </div>


  </body>
</html>

my_first_project/templates/basic_app/landing_page.html
<!DOCTYPE html>
{% extends "basic_app/BASE_html.html" %}

{% block my_block %}
<div class="container">
  <div class="jumbotron">

      <h1>Welcome! This is a Landing Page</h1>

  </div>
</div>

{% endblock %}

my_first_project/templates/basic_app/login.html
{% extends "basic_app/BASE_html.html" %}

{% block my_block %}
  <h1>Login here!</h1>
  <form  action="{% url 'basic_app:user_login' %}" method="post">
    {% csrf_token %}

    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username">

    <label for="password">Password:</label>
    <input type="password" name="password">

    <input type="submit" name="" value="Login">

  </form>
{% endblock %}

my_first_project/templates/basic_app/registration.html
<!DOCTYPE html>
{% extends "basic_app/BASE_html.html" %}

{% block my_block %}
  <div class="container">
    {% if registered %}
    <h1>Thank you for registering!</h1>
    {% else %}
    <h1>Register here!</h1>
    <h3>Fill out the form:</h3>

    <form method="post" enctype="multipart/form-data">
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Register">
    </form>

    {% endif %}
  </div>

{% endblock %}

my_first_project/templates/basic_app/relative.html
<!DOCTYPE html>

{% extends "basic_app/BASE_html.html" %}

{% block my_block %}
<div class="container">
  <div class="jumbotron">


    <ul>
      <li> <a href="{% url 'basic_app:myfunc' %}">Main Page</a> </li>
    </ul>

  </div>

</div>
{% endblock %}